# Generated by Django 5.0.6 on 2024-09-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_picture',
            field=models.ImageField(blank=True, default='opportunity_pictures/default_opportunity_image.png', null=True, upload_to='opportunity_pictures/'),
        ),
    ]
