# Generated by Django 5.0.6 on 2024-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunity_opportunity_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_picture',
            field=models.ImageField(blank=True, default='opportunity_pictures/', null=True, upload_to='opportunity_pictures/'),
        ),
    ]
