# Generated by Django 5.0.6 on 2024-09-21 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_picture'),
        ('opportunities', '0004_alter_opportunity_opportunity_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('privacy', models.CharField(choices=[('share_name_amount', 'Share my name and amount'), ('share_name_hide_amount', 'Share my name but hide amount'), ('anonymous', 'Anonymous')], max_length=30)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
