# Generated by Django 5.0.6 on 2024-09-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_organization'),
        ('opportunities', '0005_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='opportunities.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='accounts.userprofile'),
        ),
    ]
